name: MacOS CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - uses: actions/cache@v1
        name: Cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ env.GITHUB_SHA }}
          restore-keys: ${{ runner.os }}-stack-

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: '8.8.2'
          stack-version: '2.3.1'
          enable-stack: true
          stack-no-global: true
          stack-setup-ghc: true

      - run:   echo ::set-env name=GITHUB_SHA::$GITHUB_SHA
        shell: bash

      - name: Build
        run: stack build

      - name: Run Compiler Tests
        run: stack test

      - name: Run Carp Tests
        run: ./run_carp_tests.sh --no_sdl
