name: Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Install Scoop
        run: |
          iwr -useb get.scoop.sh -outfile 'install-scoop.ps1'
          ./install-scoop.ps1 -RunAsAdmin
          echo "~\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "C:\ProgramData\scoop\shims" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install Stack
        run: scoop install stack

      - uses: actions/cache@v1
        name: Cache stack dependencies
        with:
          path: C:\Users\runneradmin\AppData\Local\Programs\stack
          key: ${{ runner.os }}-stack-deps-${{ github.sha }}
          restore-keys: ${{ runner.os }}-stack-deps

      - uses: actions/cache@v1
        name: Cache stack build
        with:
          path: C:\Users\runneradmin\AppData\Roaming\stack
          key: ${{ runner.os }}-stack-build-${{ github.sha }}
          restore-keys: ${{ runner.os }}-stack-build

      - name: Build
        run: stack build

      - name: Run Compiler Tests
        run: stack test

      # Disabling sanitize-addresses because it fails with following error:
      # https://github.com/actions/virtual-environments/issues/4978
      - name: Disable Debug.sanitize-addresses
        shell: bash
        run: find ./test ./examples -type f -name '*.carp' | xargs sed 's/^\((Debug.sanitize-addresses)\)/; \1/g' -i

      - name: Run Carp Tests
        shell: bash
        run: ./scripts/run_carp_tests.sh --no_sdl
